language: android
sudo: false
jdk: oraclejdk8

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.2

android:
  components:
    # Update Android SDK Tools
    # https://docs.travis-ci.com/user/languages/android/#Installing-a-newer-SDK-Platform-Tools-revision
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - tools # to install Android SDK tools 25.1.x

    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - chmod +x gradlew

script: ./gradlew build --stacktrace
